language: node_js
node_js:
- '6'
script: NODE_ENV=test mocha test/index_tests
deploy:
  provider: heroku
  api_key:
    secure: dRWCOp7qJIr6Bf2J5texNlBHBdG0VBw55oR8epNjxZ5InHjnyoWJWOxY0vcQNlAA1clZ1RAZ3LsEkFHUUglKHJcZ7wjulAGZArbN0DkY5UUQm9HKHCQ79rdCBjhWkIEe9iQ9P1naGf+6QaigdVC6afMP3npKnOTHQ8bZSVlGGHn92kVDjN100iKOY3O2g6Y+iuwCVHJX6Al/QTr4gQBaQYDEaUI06y3SAv/4plCKRZwab7aTGCXWKkPizJFjNcXeqeHv5NR8rU6UONhNcL1nxJa4MAKW+raQQ3w6TeP50SjJQRp9a4s3jjCxjhSoocUhstQ9KdRW6GwntNbOTPfbOCt5yGWVbs8oyElji1QNdmthvwDYa6DWy1kXuODUuvY9qU+N+1izFoL0oepsNobxMLePQyv57WXgQeRvPAoiA6H8qE8a/PMVXJ3VFbwQlzS03e6AI6h5pWtxMy5zPodXm7LPDl1FCGczUnNTqs+Z1P3mg+LgDsXFbDqs9amEPu8ypyjPj67niVp0XJ4CKrgLIfM4KMuXCChYITr5FnuGIoZopVkmCR1an0tA3zhgZR+KH8jNbxjVEUsDCwP8GRKoUImhOQKMVoATCfdC362nYxq8UwAh/rm/szzl+FScmQE4ZUHfKCOROgpUkLrcyZVYgZJ+qMf87AuvKv7GdGSJPwE=
